name: Spring Boot CI/CD Workflow

on:
  pull_request:
    branches:
      - release-*
      - main
  push:
    branches:
      - develop
      - release-*
      - "!main"
      - "*"

  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to promote'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Spring Boot
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean package -DskipTests -f rbnk/pom.xml

      # Step 4: Run tests (optional)
      - name: Run tests
        run: mvn test -f rbnk/pom.xml 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Step 5: Get the repository and branch name
      - name: Get repository and branch name
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"  # Extract repo name (e.g., rnbk)
          BRANCH_NAME="${GITHUB_REF##*/}"       # Extract branch name (e.g., main)
          IMAGE_TAG="${BRANCH_NAME}"  # Create image tag with branch
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV  # Save to GITHUB_ENV for later use
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_TAG .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 7: Tag the Docker image for ECR
      - name: Tag Docker image for ECR
        run: |
          docker tag $IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/docker/$REPO_NAME:$IMAGE_TAG

      # Step 8: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/docker/$REPO_NAME:$IMAGE_TAG

  promote:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Merge Release Branch to Production
      - name: Merge Release to Production
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --all
          git checkout main
          git merge ${{ github.ref }} -m "Promoting release to production"
          git push origin main

      # Step 3: Tag Production with Release Tag
      - name: Tag Production
        run: |
          git fetch --all
          git checkout main
          git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
          git push origin ${{ github.event.inputs.tag }}

